# Generated by Django 5.2.9 on 2025-12-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_contact_email_alter_client_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
