# Generated by Django 5.2.9 on 2025-12-29 12:40

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('template_name', models.CharField(help_text='Example: congrats.html or congrats_v2.html', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of when to use this template')),
                ('template_content', models.TextField(blank=True, help_text='HTML content (alternative to template_name). If both provided, this takes priority.', null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('available_variables', models.TextField(blank=True, help_text='Comma-separated variables. Example: {{client_name}}, {{company}}, {{date}}', null=True)),
                ('mail_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='templates.mailtype')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['mail_type__name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='InlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(help_text='CID referenced in HTML template', max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('public_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('version', models.PositiveIntegerField(default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_images', to='templates.mailtype')),
            ],
            options={
                'ordering': ['mail_type', 'display_order'],
                'unique_together': {('mail_type', 'content_id', 'version')},
            },
        ),
    ]
