# Generated by Django 5.2.9 on 2025-12-30 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['mail_type__name', '-version']},
        ),
        migrations.AlterModelOptions(
            name='inlineimage',
            options={'ordering': ['mail_type', 'display_order', 'content_id']},
        ),
        migrations.AlterUniqueTogether(
            name='inlineimage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='available_variables',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_content',
            field=models.TextField(blank=True, help_text='If set, overrides template_name', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inlineimage',
            name='content_id',
            field=models.CharField(help_text='CID referenced in the HTML template', max_length=100),
        ),
        migrations.AlterField(
            model_name='inlineimage',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['mail_type', 'is_active'], name='templates_e_mail_ty_343943_idx'),
        ),
        migrations.AddIndex(
            model_name='inlineimage',
            index=models.Index(fields=['mail_type', 'content_id', 'is_active'], name='templates_i_mail_ty_dfbbf9_idx'),
        ),
        migrations.RemoveField(
            model_name='inlineimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inlineimage',
            name='updated_at',
        ),
    ]
