# Generated by Django 5.2.9 on 2025-12-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_attachmentfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='file_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
