# Generated by Django 5.2.9 on 2025-12-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_attachmentfile_file_public_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttachmentFile',
        ),
    ]
