# Generated by Django 5.2.9 on 2025-12-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_delete_emaillog'),
        ('mailings', '0001_initial'),
        ('templates', '0002_alter_emailtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maillog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Mail Log', 'verbose_name_plural': 'Mail Logs'},
        ),
        migrations.AlterModelOptions(
            name='senderemail',
            options={'verbose_name': 'Sender Email', 'verbose_name_plural': 'Sender Emails'},
        ),
        migrations.RemoveIndex(
            model_name='maillog',
            name='mailings_ma_client__bd8195_idx',
        ),
        migrations.RemoveIndex(
            model_name='maillog',
            name='mailings_ma_status_18370b_idx',
        ),
        migrations.AlterField(
            model_name='maillog',
            name='campaign_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_logs', to='client.client'),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='mail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.mailtype'),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='recipient_count',
            field=models.IntegerField(default=1, help_text='Number of recipients (usually 1 for individual logs)'),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='templates.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['client', '-sent_at'], name='mailings_ma_client__f87906_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['status', '-sent_at'], name='mailings_ma_status_34b82c_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['campaign_name'], name='mailings_ma_campaig_80fa9e_idx'),
        ),
    ]
