# Generated by Django 5.2.9 on 2025-12-31 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_delete_emaillog'),
        ('mailings', '0002_alter_maillog_options_alter_senderemail_options_and_more'),
        ('templates', '0006_delete_attachmentfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillog',
            name='body',
        ),
        migrations.RemoveField(
            model_name='maillog',
            name='recipient_count',
        ),
        migrations.AddField(
            model_name='maillog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maillog',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['sender_email'], name='mailings_ma_sender__d5aaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['created_by'], name='mailings_ma_created_a53429_idx'),
        ),
    ]
